# Generated by Django 3.2.2 on 2022-02-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='توضیحات'),
        ),
    ]
