# Generated by Django 3.2.2 on 2022-02-13 21:48

from django.db import migrations, models
import django.db.models.deletion
import hesabyar.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_header_origin'),
        ('hesabyar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hesabyar.transaction')),
                ('spend_type', models.CharField(choices=[('هزینه', 'هزینه'), ('حقوق', 'حقوق')], max_length=50, verbose_name='spend_type')),
            ],
            options={
                'verbose_name': 'Spend',
                'verbose_name_plural': 'Spends',
            },
            bases=('hesabyar.transaction', hesabyar.models.LinkHelper),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hesabyar_accounts', to='authentication.profile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('نقدی', 'نقدی'), ('کارتخوان', 'کارتخوان'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت'),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('spend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hesabyar.spend')),
                ('cost_type', models.CharField(choices=[('هزینه آب', 'هزینه آب'), ('هزینه تلفن', 'هزینه تلفن'), ('هزینه برق', 'هزینه برق'), ('هزینه اینترنت', 'هزینه اینترنت'), ('هزینه گاز', 'هزینه گاز'), ('هزینه حمل ونقل', 'هزینه حمل ونقل'), ('هزینه اجاره', 'هزینه اجاره')], max_length=50, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'Cost',
                'verbose_name_plural': 'Costs',
            },
            bases=('hesabyar.spend', hesabyar.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('spend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hesabyar.spend')),
            ],
            options={
                'verbose_name': 'Wage',
                'verbose_name_plural': 'Wages',
            },
            bases=('hesabyar.spend', hesabyar.models.LinkHelper),
        ),
    ]
