# Generated by Django 3.2.2 on 2022-02-04 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='document_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 21, 9, 29, 865738, tzinfo=utc), verbose_name='document_datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن'),
        ),
    ]
