# Generated by Django 3.2.2 on 2022-02-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesheet',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hesabyar.invoice', verbose_name='invoice'),
            preserve_default=False,
        ),
    ]
