# Generated by Django 3.2.2 on 2022-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0002_auto_20220214_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='month',
            field=models.IntegerField(default=11, verbose_name='month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wage',
            name='year',
            field=models.IntegerField(default=1400, verbose_name='year'),
            preserve_default=False,
        ),
    ]
