# Generated by Django 3.2.2 on 2022-02-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0002_auto_20220206_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hesabyar.profilefinancialaccount', verbose_name='مشتری'),
        ),
    ]
