# Generated by Django 3.2.2 on 2022-02-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0002_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('نقدی', 'نقدی'), ('کارت به کارت', 'کارت به کارت')], default='کارت به کارت', max_length=50, verbose_name='نوع پرداخت'),
        ),
    ]
