# Generated by Django 3.2.2 on 2022-02-05 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0002_alter_warehousesheet_ware_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesheet',
            name='date_registered',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 20, 14, 1, 369894, tzinfo=utc), verbose_name='date_registered'),
            preserve_default=False,
        ),
    ]
