# Generated by Django 3.2.2 on 2022-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_navlink_parent'),
        ('hesabyar', '0003_auto_20220214_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='documents',
            field=models.ManyToManyField(blank=True, to='core.Document', verbose_name='documents'),
        ),
    ]
