# Generated by Django 3.2.2 on 2022-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0003_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('فنجان', 'فنجان')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
    ]
