# Generated by Django 3.2.2 on 2022-02-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0004_transaction_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('color_origin', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], max_length=50, null=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'TransactionCategory',
                'verbose_name_plural': 'TransactionCategories',
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hesabyar.Tag', verbose_name='برچسب ها'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_origin',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], max_length=50, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='color_origin',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], max_length=50, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hesabyar.Tag', verbose_name='برچسب ها'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hesabyar.transactioncategory', verbose_name='category'),
        ),
    ]
