# Generated by Django 3.2.2 on 2022-02-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0004_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'verbose_name': 'FinancialAccount', 'verbose_name_plural': 'FinancialAccounts'},
        ),
        migrations.AddField(
            model_name='financialyear',
            name='year',
            field=models.IntegerField(default=1400, verbose_name='year'),
            preserve_default=False,
        ),
    ]
