# Generated by Django 3.2.2 on 2022-02-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0005_auto_20220206_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('پرداخت نشده', 'پرداخت نشده'), ('کارتخوان', 'کارتخوان'), ('پرداخت نقدی', 'پرداخت نقدی')], default='پرداخت نشده', max_length=50, verbose_name='نحوه پرداخت'),
        ),
    ]
