# Generated by Django 3.2.2 on 2022-02-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0006_financialbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialbalance',
            old_name='sell_benetif',
            new_name='sell_benefit',
        ),
    ]
