# Generated by Django 3.2.2 on 2022-02-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0006_financialbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hesabyar.transaction', verbose_name='transaction'),
            preserve_default=False,
        ),
    ]
