# Generated by Django 3.2.2 on 2022-02-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0007_alter_financialdocument_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('همراه بانک', 'همراه بانک'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت'),
        ),
        migrations.CreateModel(
            name='StorePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.IntegerField(default=0, verbose_name='sell_price')),
                ('buy_price', models.IntegerField(default=0, verbose_name='buy_price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('productorservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesabyar.productorservice', verbose_name='productorservice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesabyar.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'StorePrice',
                'verbose_name_plural': 'StorePrices',
            },
        ),
    ]
