# Generated by Django 3.2.2 on 2022-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0007_rename_sell_benetif_financialbalance_sell_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalance',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='financialbalance',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='هزینه'),
        ),
    ]
