# Generated by Django 3.2.2 on 2022-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0008_auto_20220217_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalance',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='buy_price',
            field=models.IntegerField(default=0, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='storeprice',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('تحویل شده', 'تحویل شده'), ('تایید شده', 'تایید شده'), ('کنسل شده', 'کنسل شده'), ('پاس شده', 'پاس شده')], default='پیش نویس', max_length=50, verbose_name='وضعیت'),
        ),
    ]
