# Generated by Django 3.2.2 on 2022-02-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0008_auto_20220216_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalance',
            name='buy_service',
            field=models.IntegerField(default=0, verbose_name='خرید خدمات'),
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='sell_service',
            field=models.IntegerField(default=0, verbose_name='فروش خدمات'),
        ),
        migrations.AddField(
            model_name='financialbalance',
            name='ship_fee',
            field=models.IntegerField(default=0, verbose_name='هزینه حمل'),
        ),
    ]
