# Generated by Django 3.2.2 on 2022-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabyar', '0010_auto_20220219_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialbalance',
            name='wage',
            field=models.IntegerField(default=0, verbose_name='حقوق'),
        ),
    ]
