# Generated by Django 3.2.2 on 2021-10-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('melli_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی')),
                ('sh_sh', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر')),
                ('stock1', models.IntegerField(default=0, verbose_name='stock1')),
                ('stock2', models.IntegerField(default=0, verbose_name='stock2')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('melli_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی')),
                ('sh_sh', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.agent', verbose_name='agent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_set', to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('value', models.IntegerField(default=0, verbose_name='value')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='stock/img/Payment', verbose_name='image')),
                ('date_paid', models.DateTimeField(verbose_name='date paid')),
                ('payment_type', models.CharField(choices=[('نقد', 'نقد'), ('چک', 'چک'), ('کارت به کارت', 'کارت به کارت'), ('پرداخت توسط بانک', 'پرداخت توسط بانک')], default='نقد', max_length=50, verbose_name='payment type')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('file', models.FileField(blank=True, null=True, upload_to='stock/img/Document', verbose_name='file')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
