# Generated by Django 3.2.2 on 2021-10-01 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('melli_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی')),
                ('sh_sh', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
