# Generated by Django 3.2.2 on 2021-06-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='نماینده است؟'),
        ),
    ]
