# Generated by Django 3.2.2 on 2021-06-18 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_agent_set', to='authentication.profile', verbose_name='agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='stock',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_set', to='authentication.profile', verbose_name='profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock1',
            field=models.IntegerField(default=0, verbose_name='stock1'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock2',
            field=models.IntegerField(default=0, verbose_name='stock2'),
        ),
    ]
