# Generated by Django 3.2.2 on 2021-10-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_agent',
        ),
        migrations.AlterField(
            model_name='stock',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.agent', verbose_name='agent'),
        ),
    ]
