# Generated by Django 3.2.2 on 2021-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_document_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='sdsd', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
