# Generated by Django 3.2.2 on 2021-06-24 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210624_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
