# Generated by Django 3.2.2 on 2021-10-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=1, verbose_name='iteration')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='success', max_length=50, verbose_name='color')),
                ('profiles', models.ManyToManyField(to='authentication.Profile', verbose_name='profiles')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
            },
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('serial_no', models.CharField(max_length=50, verbose_name='serial_no')),
                ('ip', models.CharField(default='192.168.45.200', max_length=50, verbose_name='ip')),
                ('port', models.IntegerField(default=80, verbose_name='port')),
                ('feeder_pin', models.CharField(default='09155323633@', max_length=50, verbose_name='feeder_pin')),
                ('is_protected', models.BooleanField(default=False, verbose_name='is_protected')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='bms/images/feeder/', verbose_name='thumbnail')),
            ],
            options={
                'verbose_name': 'Feeder',
                'verbose_name_plural': 'Feeders',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_protected', models.BooleanField(default=False, verbose_name='is_protected')),
                ('scenario_pin', models.CharField(default='09155323633@', max_length=50, verbose_name='pin')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('commands', models.ManyToManyField(blank=True, to='bms.Command', verbose_name='commands')),
                ('profiles', models.ManyToManyField(blank=True, to='authentication.Profile', verbose_name='profiles')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('register', models.IntegerField(verbose_name='register')),
                ('current_state', models.BooleanField(default=False, verbose_name='state')),
                ('relay_pin', models.CharField(default='09155323633@', max_length=50, verbose_name='relay_pin')),
                ('is_protected', models.BooleanField(default=False, verbose_name='protected')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.feeder', verbose_name='feeder')),
            ],
            options={
                'verbose_name': 'Relay',
                'verbose_name_plural': 'Relays',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('succeed', models.BooleanField(default=True, verbose_name='succeed')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.command', verbose_name='command')),
                ('feeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.feeder', verbose_name='feeder')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
                ('relay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.relay', verbose_name='relay')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.scenario', verbose_name='scenario')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.relay', verbose_name='relay'),
        ),
    ]
