# Generated by Django 3.2.2 on 2021-05-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_profilecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('icon_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='fa')),
                ('icon_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='material_icon')),
                ('icon_svg', models.CharField(blank=True, max_length=50, null=True, verbose_name='svg_icon')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض آیکون')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع آیکون')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Icon/', verbose_name='تصویر آیکون')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, choices=[('drassistant', 'drassistant'), ('web', 'web'), ('stock', 'stock'), ('charity', 'charity'), ('projectmanager', 'projectmanager'), ('market', 'market'), ('transport', 'transport'), ('livestock', 'livestock'), ('charirty', 'charirty'), ('core', 'core'), ('dashboard', 'dashboard'), ('realestate', 'realestate'), ('vehicles', 'vehicles'), ('projectcontrol', 'projectcontrol')], max_length=20, null=True, verbose_name='app_name')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('value_origin', models.CharField(blank=True, max_length=10000, null=True, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'پارامتر',
                'verbose_name_plural': 'پارامتر ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.icon', verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تصویر')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='شرح تصویر')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Gallery/Photo/Thumbnail/', verbose_name='تصویر کوچک')),
                ('image_main_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Gallery/Photo/Main/', verbose_name='تصویر اصلی')),
                ('image_header_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Gallery/Photo/Header/', verbose_name='تصویر سربرگ')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود?')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='موقعیت مکانی تصویر')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='افزوده شده در')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='اصلاح شده در')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'GalleryPhoto',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_home', models.BooleanField(default=False, verbose_name='for_home')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('panel', models.CharField(blank=True, max_length=50, null=True, verbose_name='panel')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='short_description')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('image_thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Page/Image/Thumbnail/', verbose_name='تصویر کوچک')),
                ('image_header_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Page/Image/Header/', verbose_name='تصویر سربرگ')),
                ('image_main_origin', models.ImageField(blank=True, null=True, upload_to='core/images/Page/Image/Main/', verbose_name='تصویر اصلی')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('color', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, null=True, verbose_name='color')),
                ('meta_data', models.CharField(max_length=100, verbose_name='MetaData')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('class_name', models.CharField(max_length=50, verbose_name='class_name')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='افزوده شده در')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='اصلاح شده در')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='creator')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.icon', verbose_name='icon')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.basicpage', verbose_name='basicpage')),
                ('tags', models.ManyToManyField(blank=True, related_name='pages', to='core.Tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'BasicPage',
                'verbose_name_plural': 'BasicPages',
            },
        ),
    ]
