# Generated by Django 3.2.2 on 2021-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زیر عنوان'),
        ),
    ]
