# Generated by Django 3.2.2 on 2021-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='app_name',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('projectmanager', 'projectmanager'), ('core', 'core'), ('market', 'market')], max_length=20, null=True, verbose_name='app_name'),
        ),
    ]
