# Generated by Django 3.2.2 on 2021-05-31 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parameter_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.basicpage', verbose_name='basicpage'),
        ),
    ]
