# Generated by Django 3.2.2 on 2021-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basicpage_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='app_name',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('stock', 'stock'), ('resume', 'resume'), ('realestate', 'realestate'), ('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('help', 'help'), ('farm', 'farm'), ('core', 'core'), ('market', 'market')], max_length=20, null=True, verbose_name='app_name'),
        ),
    ]
