# Generated by Django 3.2.2 on 2021-06-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('core', '0002_alter_parameter_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام اپ'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کلاس'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='color',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='نمایش در خانه'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='meta_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متا دیتا'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='panel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پنل'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.basicpage', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
