# Generated by Django 3.2.2 on 2021-05-31 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_basicpage_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='class_name'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='core/images/Page/Header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='image_main_origin',
            field=models.ImageField(blank=True, null=True, upload_to='core/images/Page/Main/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='image_thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='core/images/Page/Thumbnail/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='meta_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MetaData'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.basicpage', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag', verbose_name='برچسب ها'),
        ),
    ]
