# Generated by Django 3.2.2 on 2021-08-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_parameter_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='related_page',
            field=models.ManyToManyField(blank=True, to='core.BasicPage', verbose_name='BasicPage'),
        ),
    ]
