# Generated by Django 3.2.2 on 2021-08-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_basicpage_related_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpage',
            name='related_page',
        ),
        migrations.AddField(
            model_name='basicpage',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='core.BasicPage', verbose_name='صفحات مرتبط از'),
        ),
    ]
