# Generated by Django 3.2.2 on 2021-06-13 02:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='panel',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='پنل'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
