# Generated by Django 3.2.2 on 2021-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0005_auto_20211106_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='profiles',
            field=models.ManyToManyField(related_name='profile_documents', to='authentication.Profile', verbose_name='profiles'),
        ),
    ]
