# Generated by Django 3.2.2 on 2021-06-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210613_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='core.basicpage', verbose_name='والد'),
        ),
    ]
