# Generated by Django 3.2.2 on 2021-06-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_basicpage_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='app_name',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('stock', 'stock'), ('projectmanager', 'projectmanager'), ('core', 'core'), ('market', 'market')], max_length=20, null=True, verbose_name='app_name'),
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image', verbose_name='image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.basicpage', verbose_name='page')),
            ],
            options={
                'verbose_name': 'PageImage',
                'verbose_name_plural': 'PageImages',
            },
        ),
    ]
