# Generated by Django 3.2.2 on 2021-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parameter_app_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='اولویت / ترتیب'),
        ),
    ]
