# Generated by Django 3.2.2 on 2021-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210828_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='core.BasicPage', verbose_name='صفحات مرتبط'),
        ),
    ]
