# Generated by Django 3.2.2 on 2021-06-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210618_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.basicpage', verbose_name='page'),
        ),
    ]
