# Generated by Django 3.2.2 on 2021-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pageimage_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecomment',
            options={'verbose_name': 'PageComment', 'verbose_name_plural': 'PageComments'},
        ),
        migrations.AddField(
            model_name='basicpage',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status'),
        ),
    ]
