# Generated by Django 3.2.2 on 2021-09-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_basicpage_related_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.link')),
                ('app_name', models.CharField(choices=[('web', 'web'), ('stock', 'stock'), ('calendar', 'calendar'), ('resume', 'resume'), ('realestate', 'realestate'), ('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('help', 'help'), ('farm', 'farm'), ('core', 'core'), ('market', 'market')], max_length=50, verbose_name='app_name')),
            ],
            options={
                'verbose_name': 'NavLink',
                'verbose_name_plural': 'NavLinks',
            },
            bases=('core.link',),
        ),
    ]
