# Generated by Django 3.2.2 on 2021-09-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_navlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
    ]
