# Generated by Django 3.2.2 on 2021-12-06 23:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_picture_image_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\uploads'), upload_to='core/documents', verbose_name='فایل ضمیمه'),
        ),
    ]
