# Generated by Django 3.2.2 on 2022-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_basicpage_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_description'),
        ),
    ]
