# Generated by Django 3.2.2 on 2021-06-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_parameter_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='svg_icon'),
        ),
    ]
