# Generated by Django 3.2.2 on 2021-06-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_icon_icon_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageimage',
            old_name='image',
            new_name='image_origin',
        ),
    ]
