# Generated by Django 3.2.2 on 2021-06-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_image_pageimage_image_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageimage',
            old_name='image_origin',
            new_name='image',
        ),
    ]
