# Generated by Django 3.2.2 on 2021-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_image_origin_pageimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='app_name',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('stock', 'stock'), ('resume', 'resume'), ('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('core', 'core'), ('market', 'market')], max_length=20, null=True, verbose_name='app_name'),
        ),
    ]
