# Generated by Django 3.1.7 on 2021-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('latitude', models.CharField(max_length=50, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='longitude')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
            ],
            options={
                'verbose_name': 'VehicleLocation',
                'verbose_name_plural': 'VehicleLocations',
            },
        ),
    ]
