# Generated by Django 3.2.2 on 2021-08-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('scenario', models.CharField(choices=[('TOFANG_DAR', 'TOFANG_DAR'), ('GROGAN_GIR', 'GROGAN_GIR'), ('RUH', 'RUH')], max_length=50, verbose_name='scenario')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('مافیا', 'مافیا'), ('شهروند', 'شهروند')], max_length=50, verbose_name='side')),
                ('role_name', models.CharField(max_length=50, verbose_name='role')),
                ('default_count', models.IntegerField(default=0, verbose_name='default')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'God',
                'verbose_name_plural': 'Gods',
            },
        ),
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(verbose_name='نوبت')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.game', verbose_name='Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.player', verbose_name='player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'GameRole',
                'verbose_name_plural': 'GameRoles',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='god',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.player', verbose_name='god'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('night', models.IntegerField(verbose_name='night?')),
                ('role_block', models.BooleanField(default=False, verbose_name='role_block')),
                ('action_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_target_set', to='mafia.gamerole', verbose_name='role2')),
                ('game_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_doer_set', to='mafia.gamerole', verbose_name='role1')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
