# Generated by Django 3.2.2 on 2021-08-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GOD_FATHER', 'GOD_FATHER'), ('MAFIA', 'MAFIA'), ('SHARVAND', 'SHARVAND'), ('GUARD', 'GUARD'), ('SNIPPER', 'SNIPPER'), ('COWBOY', 'COWBOY'), ('TERRORIST', 'TERRORIST'), ('DOCTOR', 'DOCTOR'), ('DETECTIVE', 'DETECTIVE')], max_length=50, verbose_name='role')),
                ('turn', models.IntegerField(verbose_name='نوبت')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'GameRole',
                'verbose_name_plural': 'GameRoles',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_target_set', to='mafia.gamerole', verbose_name='role2')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.game', verbose_name='game')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_doer_set', to='mafia.gamerole', verbose_name='role1')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='roles',
            field=models.ManyToManyField(blank=True, to='mafia.GameRole', verbose_name=''),
        ),
    ]
