# Generated by Django 3.2.2 on 2021-08-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accused',
            name='game_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mafia.gamerole', verbose_name='بازیکن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accused',
            name='votes_count',
            field=models.IntegerField(default=1, verbose_name='تعداد رای های خروج'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='level',
            field=models.CharField(choices=[('ورود به دادگاه', 'ورود به دادگاه'), ('خروج از شهر', 'خروج از شهر')], default='ورود به دادگاه', max_length=50, verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='accused',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteaccused_set', to='mafia.gamerole', verbose_name='متهم'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_set', to='mafia.gamerole', verbose_name='رای دهنده'),
        ),
    ]
