# Generated by Django 3.2.2 on 2021-08-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='god',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.god', verbose_name='god'),
        ),
    ]
