# Generated by Django 3.2.2 on 2021-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerole',
            name='status',
            field=models.CharField(choices=[('زنده', 'زنده'), ('شات شده', 'شات شده'), ('اخراج شده', 'اخراج شده')], default='زنده', max_length=50, verbose_name='state'),
            preserve_default=False,
        ),
    ]
