# Generated by Django 3.2.2 on 2021-08-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0002_auto_20210829_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accused',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.gameday', verbose_name='روز بازی'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('در حال ساخت', 'در حال ساخت'), ('در حال نقش دهی', 'در حال نقش دهی'), ('معارفه', 'معارفه'), ('در حال اجرا', 'در حال اجرا'), ('بازی در فاز روز', 'بازی در فاز روز'), ('رای گیری برای ورود به دادگاه', 'رای گیری برای ورود به دادگاه'), ('رای گیری برای خروج از شهر', 'رای گیری برای خروج از شهر'), ('بازی در فاز شب', 'بازی در فاز شب'), ('تمام شده', 'تمام شده')], max_length=50, verbose_name='وضعیت بازی'),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='counter',
            field=models.IntegerField(verbose_name='شماره روز'),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.game', verbose_name='بازی'),
        ),
        migrations.AlterField(
            model_name='gamenight',
            name='counter',
            field=models.IntegerField(verbose_name='شماره شب'),
        ),
        migrations.AlterField(
            model_name='gamenight',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.game', verbose_name='بازی'),
        ),
        migrations.AlterField(
            model_name='gamenight',
            name='status',
            field=models.CharField(choices=[('در حال اجرا', 'در حال اجرا'), ('پایان یافته', 'پایان یافته')], max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.gameday', verbose_name='روز بازی'),
        ),
    ]
