# Generated by Django 3.2.2 on 2021-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0003_auto_20210815_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
