# Generated by Django 3.2.2 on 2021-08-15 20:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0004_alter_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
    ]
