# Generated by Django 3.2.2 on 2021-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0005_alter_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='mafia/images/role/', verbose_name='image'),
        ),
    ]
