# Generated by Django 3.2.2 on 2021-11-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faresume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumecategory',
            options={'verbose_name': 'ResumeCategory', 'verbose_name_plural': 'ResumeCategories'},
        ),
    ]
