# Generated by Django 3.2.2 on 2021-09-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pagelike'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='documents',
            field=models.ManyToManyField(blank=True, to='core.Document', verbose_name='documents'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('schoolpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.schoolpage')),
                ('session_no', models.IntegerField(verbose_name='جلسه شماره ؟')),
                ('start_time', models.DateTimeField(verbose_name='start')),
                ('end_time', models.DateTimeField(verbose_name='start')),
                ('active_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.activecourse', verbose_name='activecourse')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
            bases=('school.schoolpage',),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('حضور', 'حضور'), ('غیبت', 'غیبت'), ('حضور با تاخیر', 'حضور با تاخیر')], max_length=50, verbose_name='status')),
                ('enter_time', models.DateTimeField(blank=True, null=True, verbose_name='enter')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='exit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.session', verbose_name='session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
