# Generated by Django 3.2.2 on 2021-11-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(default=387, on_delete=django.db.models.deletion.CASCADE, to='school.major', verbose_name='رشته تحصیلی'),
            preserve_default=False,
        ),
    ]
