# Generated by Django 3.2.2 on 2021-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211106_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.AddField(
            model_name='major',
            name='courses',
            field=models.ManyToManyField(to='school.Course', verbose_name='واحد های درسی'),
        ),
    ]
