# Generated by Django 3.2.2 on 2021-12-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20211207_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end_date')),
            ],
            options={
                'verbose_name': 'EducationalYear',
                'verbose_name_plural': 'EducationalYears',
            },
        ),
        migrations.AddField(
            model_name='activecourse',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.educationalyear', verbose_name='سال تحصیلی'),
            preserve_default=False,
        ),
    ]
