# Generated by Django 3.2.2 on 2021-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_course_course_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='description',
            field=models.CharField(default='sdssd', max_length=500, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('حضور', 'حضور'), ('غیبت', 'غیبت'), ('نا مشخص', 'نا مشخص'), ('حضور با تاخیر', 'حضور با تاخیر')], max_length=50, verbose_name='status'),
        ),
    ]
