# Generated by Django 3.2.2 on 2021-12-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20211227_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب'), ('نا مشخص', 'نا مشخص'), ('تاخیر', 'تاخیر')], max_length=50, verbose_name='status'),
        ),
    ]
