# Generated by Django 3.2.2 on 2021-06-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_parameter_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            options={
                'verbose_name': 'MarketPage',
                'verbose_name_plural': 'MarketPages',
            },
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('marketpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketpage')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=('market.marketpage',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('marketpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketpage')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=('market.marketpage',),
        ),
    ]
