# Generated by Django 3.2.2 on 2021-09-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='buy_price',
            field=models.IntegerField(default=0, verbose_name='قیمت خرید'),
        ),
    ]
