# Generated by Django 3.2.2 on 2021-09-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='title')),
                ('supplier_profit', models.IntegerField(default=0, verbose_name='سود فروشنده')),
                ('shipper_profit', models.IntegerField(default=0, verbose_name='سود حمل کننده')),
                ('customer_profit', models.IntegerField(default=0, verbose_name='سود مشتری')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سند')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'FinancialReport',
                'verbose_name_plural': 'FinancialReports',
            },
        ),
    ]
