# Generated by Django 3.2.2 on 2021-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_category',
            field=models.BooleanField(default=True, verbose_name='نمایش در صفحه دسته بندی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='old_price',
            field=models.IntegerField(default=123300, verbose_name='قیمت قبلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_names',
            field=models.ManyToManyField(to='market.UnitName', verbose_name='unit_names'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='available',
            field=models.IntegerField(default=10, verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='unit_price',
            field=models.IntegerField(verbose_name='قیمت فروش'),
        ),
    ]
