# Generated by Django 3.2.2 on 2021-09-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shipper_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_accepted'),
        ),
    ]
