# Generated by Django 3.2.2 on 2021-12-02 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20211005_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('marketpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketpage')),
                ('shops', models.ManyToManyField(blank=True, to='market.Shop', verbose_name='shops')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
            bases=('market.marketpage',),
        ),
    ]
