# Generated by Django 3.2.2 on 2021-09-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shop_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='for_category',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بارکد'),
        ),
        migrations.CreateModel(
            name='CategoryProductTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'CategoryProductTop',
                'verbose_name_plural': 'CategoryProductTops',
            },
        ),
    ]
