# Generated by Django 3.2.2 on 2021-12-02 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('market', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.customer')),
                ('number', models.IntegerField(verbose_name='number')),
                ('menus', models.ManyToManyField(to='market.Menu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'Desk',
                'verbose_name_plural': 'Desks',
            },
            bases=('market.customer',),
        ),
    ]
