# Generated by Django 3.2.2 on 2021-09-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210905_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='col',
            field=models.IntegerField(default=4, verbose_name='col'),
        ),
    ]
