# Generated by Django 3.2.2 on 2021-09-28 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_orderline_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducttop',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 28, 22, 37, 48, 525955, tzinfo=utc), verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
