# Generated by Django 3.2.2 on 2021-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_order_date_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='employees',
            field=models.ManyToManyField(blank=True, to='market.Employee', verbose_name='کارکنان'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='warehouses',
            field=models.ManyToManyField(blank=True, to='market.WareHouse', verbose_name='warehouses'),
        ),
    ]
