# Generated by Django 3.2.2 on 2021-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210913_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_cancelled'),
        ),
    ]
