# Generated by Django 3.2.2 on 2021-09-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_offer_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('marketpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketpage')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
            bases=('market.marketpage',),
        ),
    ]
