# Generated by Django 3.2.2 on 2021-09-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_categoryproducttop_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='market.Product', verbose_name='products'),
        ),
    ]
