# Generated by Django 3.2.2 on 2021-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_customer_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='off',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
