# Generated by Django 3.2.2 on 2021-09-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_order_date_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_of_packs',
            field=models.IntegerField(default=1, verbose_name='تعداد پاکت'),
        ),
    ]
