# Generated by Django 3.2.2 on 2021-09-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('market', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
