# Generated by Django 3.2.2 on 2021-12-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_category_default_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/desk/header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AddField(
            model_name='desk',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/desk/Main/', verbose_name='تصویر اصلی'),
        ),
    ]
