# Generated by Django 3.2.2 on 2021-09-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_supplier_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ShopRegion',
                'verbose_name_plural': 'ShopRegions',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='level',
            field=models.CharField(choices=[('مشتری عادی', 'Regular'), ('همکار', 'Co Worker'), ('توزیع کننده عمده', 'Whole Sale'), ('توزیع کننده خرد', 'Retail')], default='مشتری عادی', max_length=50, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shopregion', verbose_name='shop_region'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shopregion', verbose_name='shop_region'),
        ),
    ]
