# Generated by Django 3.2.2 on 2021-09-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210909_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.shopregion', verbose_name='shop_region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.shopregion', verbose_name='shop_region'),
            preserve_default=False,
        ),
    ]
