# Generated by Django 3.2.2 on 2022-01-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20211220_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='no_ship',
            field=models.BooleanField(default=False, verbose_name='خود مشتری مراجعه و تحویل میگیرد؟'),
        ),
    ]
