# Generated by Django 3.2.2 on 2021-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210930_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت بدون تخفیف'),
        ),
    ]
