# Generated by Django 3.2.2 on 2021-09-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('سبد خرید', 'سبد خرید'), ('درحال پردازش', 'درحال پردازش'), ('کامل شده', 'کامل شده'), ('کنسل شده', 'کنسل شده'), ('درحال انتظار', 'درحال انتظار'), ('ارسال شده', 'ارسال شده'), ('تحویل شده', 'تحویل شده'), ('درحال بسته بندی', 'درحال بسته بندی'), ('پذیرفته شده', 'پذیرفته شده'), ('بسته بندی شده', 'بسته بندی شده'), ('معلق', 'معلق'), ('تایید مشتری', 'تایید مشتری')], default='سبد خرید', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('سبد خرید', 'سبد خرید'), ('درحال پردازش', 'درحال پردازش'), ('کامل شده', 'کامل شده'), ('کنسل شده', 'کنسل شده'), ('درحال انتظار', 'درحال انتظار'), ('ارسال شده', 'ارسال شده'), ('تحویل شده', 'تحویل شده'), ('درحال بسته بندی', 'درحال بسته بندی'), ('پذیرفته شده', 'پذیرفته شده'), ('بسته بندی شده', 'بسته بندی شده'), ('معلق', 'معلق'), ('تایید مشتری', 'تایید مشتری')], max_length=50, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ProductSpecification',
                'verbose_name_plural': 'ProductSpecifications',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='specification',
            field=models.ManyToManyField(blank=True, to='market.ProductSpecification', verbose_name='specifications'),
        ),
    ]
