# Generated by Django 3.2.2 on 2021-09-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210918_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='specification',
            new_name='specifications',
        ),
    ]
