# Generated by Django 3.2.2 on 2021-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210909_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('مشتری عادی', 'Regular'), ('همکار', 'Co Worker'), ('توزیع کننده عمده', 'Whole Sale'), ('توزیع کننده خرد', 'Retail')], default='مشتری عادی', max_length=50, verbose_name='level'),
        ),
    ]
