# Generated by Django 3.2.2 on 2021-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_customer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='order',
            name='no_ship',
            field=models.BooleanField(default=False, verbose_name='خود مشتری مراجعه و تحویل میگیرد؟'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('درحال پردازش', 'درحال پردازش'), ('کامل شده', 'کامل شده'), ('کنسل شده', 'کنسل شده'), ('درحال انتظار', 'درحال انتظار'), ('ارسال شده', 'ارسال شده'), ('تحویل شده', 'تحویل شده'), ('درحال بسته بندی', 'درحال بسته بندی'), ('پذیرفته شده', 'پذیرفته شده'), ('بسته بندی شده', 'بسته بندی شده'), ('معلق', 'معلق'), ('تایید مشتری', 'تایید مشتری')], max_length=50, verbose_name='status'),
        ),
    ]
