# Generated by Django 3.2.2 on 2021-09-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_rename_specification_shop_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='market.ProductFeature', verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('مشتری عادی', 'مشتری عادی'), ('همکار', 'همکار'), ('توزیع کننده عمده', 'توزیع کننده عمده'), ('توزیع کننده خرد', 'توزیع کننده خرد')], default='مشتری عادی', max_length=50, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='level',
            field=models.CharField(choices=[('مشتری عادی', 'مشتری عادی'), ('همکار', 'همکار'), ('توزیع کننده عمده', 'توزیع کننده عمده'), ('توزیع کننده خرد', 'توزیع کننده خرد')], default='مشتری عادی', max_length=50, verbose_name='level'),
        ),
    ]
