# Generated by Django 3.2.2 on 2021-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20210910_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ship_fee',
            field=models.IntegerField(default=0, verbose_name='ship_fee'),
        ),
    ]
