# Generated by Django 3.2.2 on 2021-09-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('market', '0011_supplier_ship_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('marketpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketpage')),
                ('prefix', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='پیش تعریف')),
                ('rate', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس اینترتی')),
                ('persian_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام فارسی')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
            bases=('market.marketpage',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('سرپرست', 'سرپرست'), ('نگهبان', 'نگهبان'), ('مدیر', 'مدیر'), ('فنی', 'فنی'), ('تایید نشده', 'تایید نشده'), ('حسابدار', 'حسابدار'), ('صندوقدار', 'صندوقدار')], default='تایید نشده', max_length=50, verbose_name='نقش')),
                ('degree', models.CharField(choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], default='کارشناسی', max_length=50, verbose_name='مدرک')),
                ('major', models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تحصیلی')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_employees', to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees - کارکنان',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('marketpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketpage')),
            ],
            options={
                'verbose_name': 'ProductFeature',
                'verbose_name_plural': 'فیچر های کالا ها و محصولات',
            },
            bases=('market.marketpage',),
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام انبار')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('employees', models.ManyToManyField(blank=True, to='market.Employee', verbose_name='کارکنان')),
            ],
            options={
                'verbose_name': 'WareHouse',
                'verbose_name_plural': 'انبار های کالا',
            },
        ),
        migrations.CreateModel(
            name='ProductInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_name', models.CharField(max_length=50, verbose_name='واحد')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('adder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.employee', verbose_name='ثبت کننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.product', verbose_name='کالا')),
                ('ware_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'ProductInStock',
                'verbose_name_plural': 'کالاهای موجود در انبار',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='بارکد')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سریال')),
                ('start_date', models.DateTimeField(verbose_name='شروع گارانتی')),
                ('end_date', models.DateTimeField(verbose_name='اتمام گارانتی')),
                ('orderline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.orderline', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'Guarantee',
                'verbose_name_plural': 'خدمات پس از فروش و گارانتی',
            },
        ),
    ]
