# Generated by Django 3.2.2 on 2021-09-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_brand_employee_guarantee_productfeature_productinstock_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/imags/suppier/logo/', verbose_name='logo'),
        ),
        migrations.CreateModel(
            name='OrderInWareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField(default=True, verbose_name='ورود به انبار ؟')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('adder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.employee', verbose_name='ثبت کننده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order', verbose_name='سفارش')),
                ('ware_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'ثبت سفارش در دفتر انبار',
                'verbose_name_plural': 'OrderInWareHouses',
            },
        ),
    ]
