# Generated by Django 3.2.2 on 2021-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20210913_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(default='مشتری 1', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
