# Generated by Django 3.2.2 on 2021-06-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('core', '0003_auto_20210611_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('webpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.webpage')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
            bases=('web.webpage',),
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('webpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.webpage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ResumeCategory',
                'verbose_name_plural': 'ResumeCategorys',
            },
            bases=('web.webpage',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('webpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.webpage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.resumecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
            bases=('web.webpage',),
        ),
    ]
