# Generated by Django 3.2.2 on 2021-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210828_2325'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='links',
            field=models.ManyToManyField(blank=True, to='core.Link', verbose_name='links'),
        ),
    ]
