# Generated by Django 3.2.2 on 2022-01-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoToken',
            fields=[
                ('webpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.webpage')),
            ],
            options={
                'verbose_name': 'CryptoToken',
                'verbose_name_plural': 'CryptoTokens',
            },
            bases=('web.webpage',),
        ),
    ]
