# Generated by Django 3.2.2 on 2021-06-25 20:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='body',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='بدنه'),
        ),
    ]
