# Generated by Django 3.2.2 on 2022-01-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cryptotoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotoken',
            name='coin_market_cap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='coin_market_cap'),
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='p0rice'),
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='road_map',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='roadmap'),
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='trading_view',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='trading_view'),
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vendor'),
        ),
    ]
