# Generated by Django 3.2.2 on 2021-06-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_carousel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='height',
            field=models.IntegerField(default=500, verbose_name='height'),
        ),
    ]
