# Generated by Django 3.2.2 on 2022-01-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220122_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotoken',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='vendor_img_origin',
            field=models.ImageField(blank=True, null=True, upload_to='web/img/Token/icon/', verbose_name='تصویر آیکون'),
        ),
        migrations.AddField(
            model_name='cryptotoken',
            name='vendor_url',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='vendor_url'),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='coin_market_cap',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='coin_market_cap'),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='road_map',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='roadmap'),
        ),
        migrations.AlterField(
            model_name='cryptotoken',
            name='trading_view',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='trading_view'),
        ),
    ]
