# Generated by Django 3.2.2 on 2022-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220122_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotoken',
            name='symbol',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='symbol'),
        ),
    ]
