# Generated by Django 3.2.2 on 2022-01-27 00:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cryptotoken_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات'),
        ),
    ]
