# Generated by Django 3.2.2 on 2022-01-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_ourteam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ourteam', verbose_name='ourteam'),
        ),
    ]
