# Generated by Django 3.2.2 on 2021-06-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_award_contactmessage_countdownitem_faq_feature_ourteam_ourwork_technology_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('persentage', models.IntegerField(default=10, verbose_name='percentage')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeSkill',
                'verbose_name_plural': 'ResumeSkills',
            },
        ),
    ]
