# Generated by Django 3.2.2 on 2022-01-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_webpage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image_origin',
        ),
    ]
