# Generated by Django 3.2.2 on 2022-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_testimonial_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='عنوان'),
        ),
    ]
