# Generated by Django 3.2.2 on 2021-12-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_file'),
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.Image', verbose_name='images'),
        ),
    ]
