# Generated by Django 3.2.2 on 2021-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(default=120, verbose_name='مساحت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='تعداد خواب'),
        ),
    ]
