# Generated by Django 3.2.2 on 2021-06-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20210622_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=2000000, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
