# Generated by Django 3.2.2 on 2021-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.IntegerField(default=0, verbose_name='تعداد پارکینگ'),
        ),
    ]
