# Generated by Django 3.2.2 on 2021-06-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_alter_property_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bedrooms',
            new_name='bed_rooms',
        ),
    ]
