# Generated by Django 3.2.2 on 2021-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_rename_bedrooms_property_bed_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bath_rooms',
            field=models.IntegerField(default=1, verbose_name='تعداد سرویس بهداشتی'),
        ),
    ]
