# Generated by Django 3.2.2 on 2021-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_property_bath_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='realestate/media/Property', verbose_name='image'),
        ),
    ]
