# Generated by Django 3.2.2 on 2021-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=0, verbose_name='تعداد گاراژ'),
        ),
    ]
