# Generated by Django 3.2.2 on 2021-06-21 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_auto_20210622_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
