# Generated by Django 3.2.2 on 2021-06-21 21:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیحات'),
        ),
    ]
