# Generated by Django 3.2.2 on 2021-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='location'),
        ),
    ]
