from phoenix import settings,settings_server

SITE_URL=settings.SITE_URL
ADMIN_URL=SITE_URL+'admin/'
MEDIA_URL=settings.MEDIA_URL
STATIC_URL=settings.STATIC_URL
MEDIA_ROOT=settings.MEDIA_ROOT
TIME_ZONE=settings.TIME_ZONE
STATIC_ROOT=settings.STATIC_ROOT
SERVER_ON_HEROKU=settings.SERVER_ON_HEROKU
PUSHER_IS_ENABLE=settings.PUSHER_IS_ENABLE
DEBUG=settings.DEBUG
YEAR_ADDED=settings.YEAR_ADDED

