# Generated by Django 3.2.2 on 2021-07-26 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='enter_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 12, 14, 558780, tzinfo=utc), verbose_name='enter_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.FloatField(default=0, verbose_name='وزن'),
        ),
    ]
