# Generated by Django 3.2.2 on 2021-05-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagerPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            options={
                'verbose_name': 'ProjectManagerPage',
                'verbose_name_plural': 'ProjectManagerPage',
            },
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
    ]
