# Generated by Django 3.2.2 on 2021-10-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ProjectManagerPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            options={
                'verbose_name': 'ProjectManagerPage',
                'verbose_name_plural': 'ProjectManagerPage',
            },
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس')], default='عدد', max_length=50, verbose_name='واحد')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد')),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='توضیحات')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تعریف اولیه در سیستم', 'تعریف اولیه در سیستم'), ('تحویل شده', 'تحویل شده'), ('در حال انجام', 'در حال انجام'), ('رد شده', 'رد شده'), ('پذیرفته شده', 'پذیرفته شده'), ('درخواست شده', 'درخواست شده'), ('در حال خرید', 'در حال خرید'), ('متعلق به کارفرما', 'متعلق به کارفرما')], default='درخواست شده', max_length=50, verbose_name='وضعیت')),
                ('request_type', models.CharField(choices=[('درخواست متریال', 'درخواست متریال'), ('درخواست سرویس', 'درخواست سرویس')], max_length=50, verbose_name='type')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_createds', to='projectmanager.employee', verbose_name='ثبت کننده')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_handeleds', to='projectmanager.employee', verbose_name='پاسخ دهنده')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس')], default='عدد', max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(default=0, verbose_name='unit_price')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
            ],
            options={
                'verbose_name': 'OrganizationUnit',
                'verbose_name_plural': 'OrganizationUnits',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('percentage_completed', models.IntegerField(default=0, verbose_name='درصد تکمیل پروژه')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع پروژه')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان پروژه')),
                ('weight', models.IntegerField(default=10, verbose_name='ضریب و وزن پروژه')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('unit_price', models.IntegerField(verbose_name='هزینه پیش فرض خدمات')),
                ('unit_name', models.CharField(max_length=50, verbose_name='نام واحد')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='RequestSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید'), ('درخواست شده', 'درخواست شده')], default='درخواست شده', max_length=200, verbose_name='status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.employee', verbose_name='employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.request', verbose_name='request')),
            ],
            options={
                'verbose_name': 'RequestSignature',
                'verbose_name_plural': 'RequestSignatures',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان نقطه')),
                ('location', models.CharField(max_length=1000, verbose_name='لوکیشن')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'لوکیشن',
                'verbose_name_plural': 'لوکیشن ها',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='pre_title')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='projectmanager/images/employer/image/', verbose_name='image')),
                ('logo_origin', models.ImageField(blank=True, null=True, upload_to='projectmanager/images/employer/logo/', verbose_name='logo')),
                ('home_page', models.CharField(blank=True, max_length=100, null=True, verbose_name='home page')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='postal_code')),
                ('email', models.CharField(blank=True, max_length=80, null=True, verbose_name='email')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='fax')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'درخواست سرویس',
                'verbose_name_plural': 'درخواست های سرویس',
            },
            bases=('projectmanager.request',),
        ),
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_in', to='projectmanager.employer', verbose_name='پیمانکار'),
        ),
        migrations.AddField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_out', to='projectmanager.employer', verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(blank=True, to='projectmanager.Location', verbose_name='locations'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_units',
            field=models.ManyToManyField(blank=True, to='projectmanager.OrganizationUnit', verbose_name='واحد های سازمانی'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employer', verbose_name='employer'),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.material', verbose_name='متریال')),
            ],
            options={
                'verbose_name': 'درخواست متریال',
                'verbose_name_plural': 'درخواست های متریال',
            },
            bases=('projectmanager.request',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('event_datetime', models.DateTimeField(verbose_name='event_datetime')),
                ('start_datetime', models.DateTimeField(verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end_datetime')),
                ('locations', models.ManyToManyField(blank=True, to='projectmanager.Location', verbose_name='locations')),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='EmployeeSpeciality',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('max', models.IntegerField(verbose_name='max')),
                ('value', models.IntegerField(verbose_name='value')),
                ('percent', models.IntegerField(verbose_name='percent')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'EmployeeSpeciality',
                'verbose_name_plural': 'EmployeeSpecialitys',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.organizationunit', verbose_name='organizationunit'),
        ),
    ]
