# Generated by Django 3.2.2 on 2021-06-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('unit_price', models.IntegerField(verbose_name='هزینه پیش فرض خدمات')),
                ('unit_name', models.CharField(max_length=50, verbose_name='نام واحد')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه')], default='عدد', max_length=50, verbose_name='واحد')),
                ('unit_price', models.IntegerField(verbose_name='فی')),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='توضیحات')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تعریف اولیه در سیستم', 'تعریف اولیه در سیستم'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'در حال بررسی'), ('رد شده', 'رد شده'), ('پذیرفته شده', 'پذیرفته شده'), ('درخواست شده', 'درخواست شده'), ('در حال خرید', 'در حال خرید'), ('متعلق به کارفرما', 'متعلق به کارفرما')], default='درخواست شده', max_length=50, verbose_name='وضعیت')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='تحویل گیرنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='پروژه')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'درخواست سرویس',
                'verbose_name_plural': 'درخواست های سرویس',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید'), ('درخواست شده', 'درخواست شده')], default='درخواست شده', max_length=200, verbose_name='status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.servicerequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'امضای درخواست سرویس',
                'verbose_name_plural': 'امضا های درخواست سرویس',
            },
        ),
    ]
