# Generated by Django 3.2.2 on 2021-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='projectmanager/images/employer/logo/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='projectmanager/images/employer/image/', verbose_name='image'),
        ),
    ]
