# Generated by Django 3.2.2 on 2021-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='projectmanager/images/employer/', verbose_name='image'),
        ),
    ]
