# Generated by Django 3.2.2 on 2021-10-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_name',
            field=models.CharField(default='سرویس', max_length=50, verbose_name='نام واحد'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='هزینه پیش فرض خدمات'),
        ),
    ]
