# Generated by Django 3.2.2 on 2021-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('درخواست متریال', 'درخواست متریال'), ('درخواست سرویس', 'درخواست سرویس')], default='dddd', max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
    ]
