# Generated by Django 3.2.2 on 2021-06-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_employer_image_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='pre_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pre_title'),
        ),
    ]
