# Generated by Django 3.2.2 on 2021-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_servicerequest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='ضریب و وزن پروژه'),
        ),
    ]
