# Generated by Django 3.2.2 on 2021-06-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_service_servicerequest_servicerequestsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects_in', to='projectmanager.employer', verbose_name='contractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects_out', to='projectmanager.employer', verbose_name='employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='organization_units',
            field=models.ManyToManyField(blank=True, to='projectmanager.OrganizationUnit', verbose_name='organization_units'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس')], default='عدد', max_length=50, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس')], default='عدد', max_length=50, verbose_name='واحد'),
        ),
    ]
