# Generated by Django 3.2.2 on 2021-07-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20210717_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_in', to='projectmanager.employer', verbose_name='پیمانکار'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_out', to='projectmanager.employer', verbose_name='کارفرما'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization_units',
            field=models.ManyToManyField(blank=True, to='projectmanager.OrganizationUnit', verbose_name='واحد های سازمانی'),
        ),
    ]
