# Generated by Django 3.2.2 on 2021-10-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20211003_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('organizationunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.organizationunit')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'WareHouse',
                'verbose_name_plural': 'WareHouses',
            },
            bases=('projectmanager.organizationunit',),
        ),
        migrations.CreateModel(
            name='WareHouseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial_no')),
                ('direction', models.CharField(choices=[('ورود به انبار', 'ورود به انبار'), ('خروج از انبار', 'خروج از انبار')], max_length=50, verbose_name='direction')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_imported', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ورود')),
                ('date_exported', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee', verbose_name='employee')),
                ('material_requests', models.ManyToManyField(blank=True, to='projectmanager.MaterialRequest', verbose_name='materialrequests')),
                ('ware_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'WareHouseSheet',
                'verbose_name_plural': 'WareHouseSheets',
            },
        ),
    ]
