# Generated by Django 3.2.2 on 2021-06-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_completed',
            field=models.IntegerField(default=0, verbose_name='درصد تکمیل پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع پروژه'),
        ),
    ]
