# Generated by Django 3.2.2 on 2021-10-05 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_warehouse_warehousesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.warehousesheet', verbose_name='warehousesheet'),
        ),
    ]
