# Generated by Django 3.2.2 on 2021-06-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projectmanager', '0003_auto_20210604_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_in', to='projectmanager.employer', verbose_name='contractor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_out', to='projectmanager.employer', verbose_name='employer'),
        ),
    ]
