# Generated by Django 3.2.2 on 2021-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_employer_pre_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialrequestsignature',
            old_name='materialrequest',
            new_name='material_request',
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه')], default='عدد', max_length=50, verbose_name='unit_name'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تعریف اولیه در سیستم', 'تعریف اولیه در سیستم'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'در حال بررسی'), ('رد شده', 'رد شده'), ('پذیرفته شده', 'پذیرفته شده'), ('درخواست شده', 'درخواست شده'), ('در حال خرید', 'در حال خرید'), ('متعلق به کارفرما', 'متعلق به کارفرما')], default='درخواست شده', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه')], default='عدد', max_length=50, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='materialrequestsignature',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید'), ('درخواست شده', 'درخواست شده')], default='درخواست شده', max_length=200, verbose_name='status'),
        ),
    ]
