# Generated by Django 3.2.2 on 2021-09-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_servicerequest_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequestsignature',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='servicerequestsignature',
            name='service_request',
        ),
        migrations.DeleteModel(
            name='MaterialRequestSignature',
        ),
        migrations.DeleteModel(
            name='ServiceRequestSignature',
        ),
    ]
