# Generated by Django 3.2.2 on 2021-06-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profilecontact'),
        ('projectmanager', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر')], default='عدد', max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(default=0, verbose_name='unit_price')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_name', models.CharField(max_length=50, verbose_name='واحد')),
                ('unit_price', models.IntegerField(verbose_name='فی')),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='توضیحات')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تعریف اولیه در سیستم', 'تعریف اولیه در سیستم'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'در حال بررسی'), ('رد شده', 'رد شده'), ('پذیرفته شده', 'پذیرفته شده'), ('در حال خرید', 'در حال خرید'), ('متعلق به کارفرما', 'متعلق به کارفرما')], default='DEFAULT', max_length=50, verbose_name='وضعیت')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.material', verbose_name='متریال')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='تحویل گیرنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'درخواست متریال',
                'verbose_name_plural': 'درخواست های متریال',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید')], default='DEFAULT', max_length=200, verbose_name='status')),
                ('materialrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.materialrequest', verbose_name='درخواست')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'امضای درخواست متریال',
                'verbose_name_plural': 'امضا های درخواست متریال',
            },
        ),
    ]
