# Generated by Django 3.2.2 on 2021-10-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_warehouse_warehousesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesheet',
            name='col',
            field=models.IntegerField(blank=True, null=True, verbose_name='ردیف'),
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='shelf',
            field=models.IntegerField(blank=True, null=True, verbose_name='کمد'),
        ),
    ]
