# Generated by Django 3.2.2 on 2021-08-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_project_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان نقطه')),
                ('location', models.CharField(max_length=1000, verbose_name='لوکیشن')),
            ],
            options={
                'verbose_name': 'لوکیشن',
                'verbose_name_plural': 'لوکیشن ها',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='adder',
        ),
        migrations.DeleteModel(
            name='ProjectLocation',
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(blank=True, to='projectmanager.Location', verbose_name='locations'),
        ),
    ]
