# Generated by Django 3.2.2 on 2021-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20211008_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseexportsheet',
            options={'verbose_name': 'WareHouseExportSheet', 'verbose_name_plural': 'WareHouseExportSheets'},
        ),
        migrations.RenameField(
            model_name='warehousematerial',
            old_name='unit_price',
            new_name='unit_price_origin',
        ),
        migrations.AddField(
            model_name='warehousematerial',
            name='quantity_origin',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
