# Generated by Django 3.2.2 on 2021-10-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_materialrequest_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousesheet',
            name='material',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='material_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.materialrequest', verbose_name='material_request'),
            preserve_default=False,
        ),
    ]
