# Generated by Django 3.2.2 on 2021-06-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_material_materialrequest_materialrequestsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر')], default='عدد', max_length=50, verbose_name='واحد'),
        ),
    ]
