# Generated by Django 3.2.2 on 2021-08-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20210809_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='projectmanager.Location', verbose_name='locations'),
        ),
    ]
