# Generated by Django 3.2.2 on 2021-08-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_auto_20210810_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='employer',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fax'),
        ),
        migrations.AddField(
            model_name='employer',
            name='home_page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='home page'),
        ),
        migrations.AddField(
            model_name='employer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='postal_code'),
        ),
        migrations.AddField(
            model_name='employer',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tel'),
        ),
    ]
