# Generated by Django 3.2.2 on 2021-10-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_rename_quantity_origin_warehousematerial_sum_quantity_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='ware_house_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.warehousesheet', verbose_name='برگه انبار'),
        ),
        migrations.AlterField(
            model_name='warehousesheetline',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='unit_price'),
        ),
    ]
