# Generated by Django 3.2.2 on 2021-08-09 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projectmanager', '0005_event_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='location',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
