# Generated by Django 3.2.2 on 2021-10-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_remove_materialrequest_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousesheet',
            name='material_request',
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='material_requests',
            field=models.ManyToManyField(to='projectmanager.MaterialRequest', verbose_name='materialrequests'),
        ),
    ]
