# Generated by Django 3.2.2 on 2021-10-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20211009_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
    ]
