# Generated by Django 3.2.2 on 2021-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20210810_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
