# Generated by Django 3.2.2 on 2021-10-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_auto_20211007_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousesheet',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='date_exited',
        ),
        migrations.RemoveField(
            model_name='warehousesheet',
            name='sheet_no',
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='date_exported',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خروج'),
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='date_imported',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ورود'),
        ),
    ]
