# Generated by Django 3.2.2 on 2021-08-14 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_alter_employer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 10, 37, 17, 480069, tzinfo=utc), verbose_name='end_datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 10, 37, 19, 879578, tzinfo=utc), verbose_name='start_datetime'),
            preserve_default=False,
        ),
    ]
