# Generated by Django 3.2.2 on 2021-10-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_alter_requestsignature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_requested',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='request',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_handeleds', to='projectmanager.employee', verbose_name='پاسخ دهنده درخواست'),
        ),
    ]
