# Generated by Django 3.2.2 on 2021-11-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_auto_20211031_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'رویداد ها'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'لوکیشن ها'},
        ),
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'verbose_name': 'MaterialRequest', 'verbose_name_plural': 'درخواست های متریال'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'ServiceRequest', 'verbose_name_plural': 'درخواست های سرویس'},
        ),
    ]
