# Generated by Django 3.2.2 on 2021-11-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0009_auto_20211112_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='ware_house_sheets',
            field=models.ManyToManyField(related_name='ware_house_sheets', to='projectmanager.WareHouseSheet', verbose_name='برگه های انبار'),
        ),
    ]
