# Generated by Django 3.2.2 on 2021-09-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0009_auto_20210821_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('تن', 'تن'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('سرویس', 'سرویس')], default='عدد', max_length=50, verbose_name='واحد')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد')),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='توضیحات')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تعریف اولیه در سیستم', 'تعریف اولیه در سیستم'), ('تحویل شده', 'تحویل شده'), ('در حال انجام', 'در حال انجام'), ('رد شده', 'رد شده'), ('پذیرفته شده', 'پذیرفته شده'), ('درخواست شده', 'درخواست شده'), ('در حال خرید', 'در حال خرید'), ('متعلق به کارفرما', 'متعلق به کارفرما')], default='درخواست شده', max_length=50, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_createds', to='projectmanager.employee', verbose_name='ثبت کننده')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_handeleds', to='projectmanager.employee', verbose_name='پاسخ دهنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='RequestSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید'), ('درخواست شده', 'درخواست شده')], default='درخواست شده', max_length=200, verbose_name='status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.employee', verbose_name='employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.request', verbose_name='request')),
            ],
            options={
                'verbose_name': 'RequestSignature',
                'verbose_name_plural': 'RequestSignatures',
            },
        ),
    ]
