# Generated by Django 3.2.2 on 2021-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_materialrequest_ware_house_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default ?'),
        ),
    ]
