# Generated by Django 3.2.2 on 2021-12-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_auto_20211206_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='is default ?'),
        ),
    ]
