# Generated by Django 3.2.2 on 2021-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_location_title'),
        ('projectmanager', '0012_alter_project_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='creator',
        ),
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='map.Location', verbose_name='locations'),
        ),
    ]
