# Generated by Django 3.2.2 on 2021-12-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_auto_20211206_0116'),
        ('salary', '0002_alter_worksite_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
