# Generated by Django 3.2.2 on 2022-02-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0015_auto_20211209_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleForm',
            fields=[
                ('projectmanagerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.projectmanagerpage')),
            ],
            options={
                'verbose_name': 'SampleForm',
                'verbose_name_plural': 'SampleForms',
            },
            bases=('projectmanager.projectmanagerpage',),
        ),
    ]
