# Generated by Django 3.2.2 on 2022-02-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0017_auto_20220212_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleform',
            options={'verbose_name': 'SampleForm', 'verbose_name_plural': 'فرم های اداری نمونه'},
        ),
    ]
