# Generated by Django 3.2.2 on 2021-07-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecontact',
            name='bs_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bootstrap class'),
        ),
        migrations.AddField(
            model_name='profilecontact',
            name='icon',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
    ]
