# Generated by Django 3.2.2 on 2022-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_membershiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecontact',
            name='url',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='profilecontact',
            name='icon',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='icon'),
        ),
    ]
