# Generated by Django 3.2.2 on 2021-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210702_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontact',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
    ]
