# Generated by Django 3.2.2 on 2022-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220129_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/header/', verbose_name='header_origin'),
        ),
    ]
