# Generated by Django 3.2.2 on 2021-06-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profilecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile'),
        ),
    ]
