# Generated by Django 3.2.2 on 2021-10-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_link_new_tab'),
        ('projectmanager', '0004_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('month_name', models.CharField(max_length=50, verbose_name='ماه')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('date_paid', models.DateTimeField(verbose_name='تاریخ واریز')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'EmployeeSalary',
                'verbose_name_plural': 'EmployeeSalarys',
            },
        ),
        migrations.CreateModel(
            name='SalaryPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='SalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('مزایا', 'مزایا'), ('کسورات', 'کسورات')], default='مزایا', max_length=50, verbose_name='جهت')),
                ('title', models.CharField(choices=[('حقوق پایه', 'حقوق پایه'), ('حق فرزند', 'حق فرزند'), ('حق همسر', 'حق همسر'), ('بدی آب و هوا', 'بدی آب و هوا'), ('مالیات', 'مالیات')], max_length=50, verbose_name='عنوان')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.employeesalary', verbose_name='employeesalary')),
            ],
            options={
                'verbose_name': 'SalaryLine',
                'verbose_name_plural': 'SalaryLines',
            },
        ),
    ]
