# Generated by Django 3.2.2 on 2021-10-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_basicpage_keywords'),
        ('projectmanager', '0003_auto_20211010_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.IntegerField(verbose_name='حقوق پایه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'EmployeeSalary',
                'verbose_name_plural': 'EmployeeSalarys',
            },
        ),
    ]
