# Generated by Django 3.2.2 on 2021-10-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_auto_20211014_0413'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.location', verbose_name='location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.worksite', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'WorkSite',
                'verbose_name_plural': 'WorkSites',
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('employees_origin', models.ManyToManyField(blank=True, to='projectmanager.Employee', verbose_name='employees')),
                ('organization_units', models.ManyToManyField(blank=True, to='projectmanager.OrganizationUnit', verbose_name='واحد های سازمانی')),
            ],
            options={
                'verbose_name': 'WorkGroup',
                'verbose_name_plural': 'WorkGroups',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='روز')),
                ('date_entered', models.TimeField(verbose_name='ورود')),
                ('date_exited', models.TimeField(verbose_name='خروج')),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.workgroup', verbose_name='گروه کاری')),
                ('work_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.worksite', verbose_name='محل کار')),
            ],
            options={
                'verbose_name': 'WorkDay',
                'verbose_name_plural': 'WorkDays',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(blank=True, null=True, verbose_name='ورود')),
                ('date_exited', models.DateTimeField(blank=True, null=True, verbose_name='خروج')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee', verbose_name='employee')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.workday', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
