# Generated by Django 3.2.2 on 2021-10-11 23:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='base_salary',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='date_paid',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 16, 25, 795158, tzinfo=utc), verbose_name='تاریخ واریز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='month',
            field=models.IntegerField(default=1, verbose_name='ماه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='month_name',
            field=models.CharField(default='sdsds', max_length=50, verbose_name='ماه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='year',
            field=models.IntegerField(default=1, verbose_name='سال'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('مزایا', 'مزایا'), ('کسورات', 'کسورات')], default='مزایا', max_length=50, verbose_name='جهت')),
                ('title', models.CharField(choices=[('حقوق پایه', 'حقوق پایه'), ('حق فرزند', 'حق فرزند'), ('حق همسر', 'حق همسر'), ('بدی آب و هوا', 'بدی آب و هوا'), ('مالیات', 'مالیات')], max_length=50, verbose_name='عنوان')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.employeesalary', verbose_name='employeesalary')),
            ],
            options={
                'verbose_name': 'SalaryLine',
                'verbose_name_plural': 'SalaryLines',
            },
        ),
    ]
