# Generated by Django 3.2.2 on 2021-12-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_location_title'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.location', verbose_name='location'),
        ),
    ]
