# Generated by Django 3.2.4 on 2021-10-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_attendance_workday_workgroup_worksite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='attendance_date',
            new_name='work_date',
        ),
        migrations.RenameField(
            model_name='workday',
            old_name='date_exited',
            new_name='work_end',
        ),
        migrations.RenameField(
            model_name='workday',
            old_name='date_entered',
            new_name='work_start',
        ),
    ]
