# Generated by Django 3.2.2 on 2021-10-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20211015_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.workday', verbose_name='work_day'),
        ),
    ]
