# Generated by Django 3.2.2 on 2021-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='reserved',
            field=models.IntegerField(default=False, verbose_name='reserved'),
        ),
    ]
