# Generated by Django 3.2.2 on 2021-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='reserved'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservedmeal',
            name='date_reserved',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_reserved'),
        ),
    ]
