# Generated by Django 3.2.2 on 2021-11-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_served', models.DateField(verbose_name='date_served')),
                ('meal_type', models.CharField(choices=[('صبحانه', 'صبحانه'), ('ناهار', 'ناهار'), ('شام', 'شام')], max_length=50, verbose_name='meal type')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food', verbose_name='food')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='ReservedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateTimeField(verbose_name='date_reserved')),
                ('date_served', models.DateTimeField(blank=True, null=True, verbose_name='date_served')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.guest', verbose_name='guest')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal', verbose_name='meal')),
            ],
            options={
                'verbose_name': 'ReservedMeal',
                'verbose_name_plural': 'ReservedMeals',
            },
        ),
    ]
