# Generated by Django 3.2.2 on 2021-12-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='max_reserve',
            field=models.IntegerField(default=100, verbose_name='max'),
        ),
    ]
