# Generated by Django 3.2.2 on 2021-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedmeal',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
