# Generated by Django 3.2.2 on 2021-10-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('تویوتا', 'تویوتا'), ('بنز', 'بنز'), ('ایسوزو', 'ایسوزو'), ('اسکانیا', 'اسکانیا'), ('مزدا', 'مزدا'), ('ولوو', 'ولوو'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='تویوتا', max_length=50, verbose_name='برند'),
        ),
    ]
