# Generated by Django 3.2.2 on 2021-11-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_document_file'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_license_photoes', to='core.image', verbose_name='تصویر گواهینامه'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_license_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_license_photoes', to='core.image', verbose_name='تصویر کارت بهداشت'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='vehicles.Passenger', verbose_name='مسافر ها'),
        ),
    ]
