# Generated by Django 3.2.2 on 2021-10-03 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleevent',
            name='event_time',
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 18, 6, 58, 654314, tzinfo=utc), verbose_name='event_datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('شستشو', 'شستشو'), ('آب رادیات جدید', 'آب رادیات جدید'), ('سوخت جدید', 'سوخت جدید'), ('تعمیر موتور', 'تعمیر موتور'), ('تعمیر گیربکس', 'تعمیر گیربکس'), ('بیمه جدید', 'بیمه جدید'), ('لاستیک جدید', 'لاستیک جدید'), ('زنجیر جدید', 'زنجیر جدید'), ('شیشه جدید', 'شیشه جدید'), ('تعویض روغن', 'تعویض روغن'), ('فیلتر هوای جدید', 'فیلتر هوای جدید'), ('فیلتر روغن جدید', 'فیلتر روغن جدید')], max_length=100, verbose_name='سرویس'),
        ),
    ]
