# Generated by Django 3.2.4 on 2021-10-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_auto_20211014_0413'),
        ('vehicles', '0003_auto_20211003_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2015, verbose_name='سال تولید'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('distance', models.IntegerField(default=5, verbose_name='distance')),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_tripped', models.DateTimeField(verbose_name='date_tripped')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_desctination_set', to='projectmanager.location', verbose_name='مقصد')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver', verbose_name='driver')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_source_set', to='projectmanager.location', verbose_name='مبدا')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
