# Generated by Django 3.2.2 on 2021-10-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projectmanager', '0006_auto_20211020_1718'),
        ('vehicles', '0004_auto_20211018_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
            ],
            options={
                'verbose_name': 'TripCategory',
                'verbose_name_plural': 'TripCategorys',
            },
        ),
        migrations.RemoveField(
            model_name='trip',
            name='date_tripped',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='source',
        ),
        migrations.AddField(
            model_name='trip',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان سرویس'),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع سرویس'),
        ),
        migrations.AddField(
            model_name='trip',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='تاخیر'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('درخواست شده', 'درخواست شده'), ('تأیید شده', 'تأیید شده'), ('کنسل شده', 'کنسل شده'), ('تحویل شده', 'تحویل شده')], default='درخواست شده', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('تویوتا', 'تویوتا'), ('پژو', 'پژو'), ('بنز', 'بنز'), ('ایسوزو', 'ایسوزو'), ('اسکانیا', 'اسکانیا'), ('مزدا', 'مزدا'), ('ولوو', 'ولوو'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='تویوتا', max_length=50, verbose_name='برند'),
        ),
        migrations.CreateModel(
            name='TripPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('distance', models.IntegerField(default=0, verbose_name='فاصله')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت زمان تقریبی')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destination_set', to='projectmanager.location', verbose_name='مقصد')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_source_set', to='projectmanager.location', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'TripPath',
                'verbose_name_plural': 'TripPaths',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.tripcategory', verbose_name='نوع سفر'),
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(to='vehicles.Passenger', verbose_name='مسافر ها'),
        ),
        migrations.AddField(
            model_name='trip',
            name='paths',
            field=models.ManyToManyField(blank=True, to='vehicles.TripPath', verbose_name='مسیر های سرویس'),
        ),
    ]
