# Generated by Django 3.2.2 on 2021-10-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('vehicles', '0004_auto_20211018_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('تویوتا', 'تویوتا'), ('پژو', 'پژو'), ('بنز', 'بنز'), ('ایسوزو', 'ایسوزو'), ('اسکانیا', 'اسکانیا'), ('مزدا', 'مزدا'), ('ولوو', 'ولوو'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='تویوتا', max_length=50, verbose_name='برند'),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='passerngers',
            field=models.ManyToManyField(to='vehicles.Passenger', verbose_name='مسافر ها'),
        ),
    ]
