# Generated by Django 3.2.2 on 2021-10-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20211024_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleworkevent',
            name='work_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.workshift', verbose_name='شیفت کاری'),
        ),
    ]
