# Generated by Django 3.2.2 on 2021-10-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20211020_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='passerngers',
            new_name='passengers',
        ),
    ]
