# Generated by Django 3.2.2 on 2021-10-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_rename_passerngers_trip_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_ended'),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_started'),
        ),
    ]
