# Generated by Django 3.2.2 on 2021-10-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20211020_1718'),
        ('vehicles', '0007_auto_20211020_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date_tripped',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='source',
        ),
        migrations.AddField(
            model_name='trip',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='تاخیر'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان سرویس'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع سرویس'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='توضیحات'),
        ),
        migrations.CreateModel(
            name='TripPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_desctination_set', to='projectmanager.location', verbose_name='مقصد')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_source_set', to='projectmanager.location', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'TripPath',
                'verbose_name_plural': 'TripPaths',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='paths',
            field=models.ManyToManyField(blank=True, to='vehicles.TripPath', verbose_name='مسیر های سرویس'),
        ),
    ]
