# Generated by Django 3.2.2 on 2021-10-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20211020_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'TripCategory',
                'verbose_name_plural': 'TripCategorys',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.tripcategory', verbose_name='نوع سفر'),
        ),
    ]
