# Generated by Django 3.2.2 on 2021-10-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_tripcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippath',
            name='distance',
            field=models.IntegerField(default=0, verbose_name='فاصله'),
        ),
        migrations.AddField(
            model_name='trippath',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='مدت زمان تقریبی'),
        ),
    ]
