# Generated by Django 3.2.2 on 2021-10-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20211020_1718'),
        ('vehicles', '0011_auto_20211020_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippath',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destination_set', to='projectmanager.location', verbose_name='مقصد'),
        ),
    ]
