# Generated by Django 3.2.2 on 2021-10-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_trippath_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('درخواست شده', 'درخواست شده'), ('تأیید شده', 'تأیید شده'), ('کنسل شده', 'کنسل شده'), ('تحویل شده', 'تحویل شده')], default='درخواست شده', max_length=50, verbose_name='status'),
        ),
    ]
