# Generated by Django 3.2.2 on 2021-06-13 02:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slogan',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='slogan'),
        ),
    ]
