# Generated by Django 3.2.2 on 2021-06-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('messenger', '0002_alter_message_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PusherBeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('instance_id', models.CharField(max_length=100, verbose_name='instanse_id')),
                ('authorization', models.CharField(max_length=200, verbose_name='authorization')),
            ],
            options={
                'verbose_name': 'PusherBeam',
                'verbose_name_plural': 'PusherBeams',
            },
        ),
        migrations.CreateModel(
            name='PusherChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=20, verbose_name='channel_name')),
                ('app_id', models.CharField(max_length=20, verbose_name='app_id')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('secret', models.CharField(max_length=50, verbose_name='secret')),
                ('cluster', models.CharField(default='us2', max_length=20, verbose_name='cluster')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='PusherChannelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('event_name', models.CharField(max_length=50, verbose_name='event')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.pusherchannel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'ChannelEvent',
                'verbose_name_plural': 'ChannelEvents',
            },
        ),
        migrations.CreateModel(
            name='PusherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('channelevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.pusherchannelevent', verbose_name='کانال')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='PusherBeamInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50, verbose_name='interest')),
                ('beam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.pusherbeam', verbose_name='beam')),
            ],
            options={
                'verbose_name': 'PusherBeamInterest',
                'verbose_name_plural': 'PusherBeamInterests',
            },
        ),
        migrations.CreateModel(
            name='ProfileChannelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.pusherchannelevent', verbose_name='channel_event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ProfileChannelEvent',
                'verbose_name_plural': 'ProfileChannelEvents',
            },
        ),
    ]
