# Generated by Django 3.2.2 on 2021-09-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.message')),
            ],
            bases=('messenger.message',),
        ),
    ]
