# Generated by Django 3.2.2 on 2021-08-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20210813_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='event',
        ),
        migrations.AddField(
            model_name='member',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messenger.channel', verbose_name='channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
    ]
