# Generated by Django 3.2.2 on 2021-08-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20210813_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='event',
            field=models.CharField(default='DEFAULT', max_length=50, verbose_name='event'),
        ),
    ]
