# Generated by Django 3.2.2 on 2021-07-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_profilecontact_icon'),
        ('core', '0016_alter_parameter_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'english'), ('dutch', 'dutch'), ('farsi', 'farsi'), ('russian', 'russian'), ('arabic', 'arabic')], default='english', max_length=50, verbose_name='language')),
                ('image_header_origin', models.ImageField(blank=True, null=True, upload_to='resume/img/Resume/Header/', verbose_name='تصویر سربرگ')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('typing_text', models.CharField(blank=True, default='Developer,Designer,Programmer', max_length=500, null=True, verbose_name='typing_text')),
                ('about_top', models.TextField(blank=True, null=True, verbose_name='about_top')),
                ('image_main_origin', models.ImageField(blank=True, null=True, upload_to='resume/img/Resume/Main/', verbose_name='تصویر اصلی')),
                ('job_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='job_title')),
                ('about_middle', models.TextField(blank=True, null=True, verbose_name='about_middle')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='birth_day')),
                ('website', models.CharField(blank=True, max_length=500, null=True, verbose_name='website')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='degree')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('freelance', models.CharField(blank=True, max_length=100, null=True, verbose_name='freelance')),
                ('about_bottom', models.TextField(blank=True, null=True, verbose_name='about_bottom')),
                ('facts_top', models.TextField(blank=True, null=True, verbose_name='facts_top')),
                ('skills_top', models.TextField(blank=True, null=True, verbose_name='skills_top')),
                ('resume_top', models.TextField(blank=True, null=True, verbose_name='resume_top')),
                ('portfolio_top', models.TextField(blank=True, null=True, verbose_name='portfolio_top')),
                ('services_top', models.TextField(blank=True, null=True, verbose_name='services_top')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ResumeIndex',
                'verbose_name_plural': 'ResumeIndexs',
            },
        ),
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='ResumeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller', models.CharField(max_length=2000, verbose_name='teller')),
                ('teller_description', models.CharField(max_length=2000, verbose_name='teller_description')),
                ('title', models.CharField(max_length=2000, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=2000, null=True, verbose_name='متن')),
                ('footer', models.CharField(max_length=200, verbose_name='پانوشت')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('date_added', models.DateField(verbose_name='date_added')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='resume/img/Testimonial/', verbose_name='تصویر')),
                ('resume_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeindex', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('percentage', models.IntegerField(default=10, verbose_name='percentage')),
                ('priority', models.IntegerField(default=10, verbose_name='priority')),
                ('resume_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeindex', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeSkill',
                'verbose_name_plural': 'ResumeSkills',
            },
        ),
        migrations.CreateModel(
            name='ResumeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('icon', models.CharField(choices=[('<i class="bi bi-emoji-smile"></i>', '<i class="bi bi-emoji-smile"></i>'), ('<i class="bi bi-journal-richtext"></i>', '<i class="bi bi-journal-richtext"></i>'), ('<i class="bi bi-headset"></i>', '<i class="bi bi-headset"></i>'), ('<i class="bi bi-award"></i>', '<i class="bi bi-award"></i>')], max_length=100, verbose_name='icon')),
                ('count', models.IntegerField(default=10, verbose_name='count')),
                ('resume_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeindex', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeFact',
                'verbose_name_plural': 'ResumeFacts',
            },
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('resume_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeindex', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeCategory',
                'verbose_name_plural': 'ResumeCategorys',
            },
        ),
        migrations.CreateModel(
            name='ResumeService',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
                ('resume_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeindex', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeService',
                'verbose_name_plural': 'ResumeServices',
            },
            bases=('resume.resumepage',),
        ),
        migrations.CreateModel(
            name='ResumePortfolio',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
                ('filter', models.CharField(choices=[('app', 'app'), ('card', 'card'), ('web', 'web')], default='web', max_length=50, verbose_name='filter')),
                ('category', models.CharField(max_length=500, verbose_name='category')),
                ('resume_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeindex', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
            bases=('resume.resumepage',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
            bases=('resume.resumepage',),
        ),
    ]
