# Generated by Django 3.2.2 on 2021-06-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('core', '0011_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            bases=('core.basicpage',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
            bases=('resume.resumepage',),
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('persentage', models.IntegerField(default=10, verbose_name='percentage')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeSkill',
                'verbose_name_plural': 'ResumeSkills',
            },
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ResumeCategory',
                'verbose_name_plural': 'ResumeCategorys',
            },
            bases=('resume.resumepage',),
        ),
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumecategory', verbose_name='category'),
        ),
    ]
