# Generated by Django 3.2.2 on 2021-06-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeskill',
            name='priority',
            field=models.IntegerField(default=10, verbose_name='priority'),
        ),
    ]
