# Generated by Django 3.2.2 on 2022-01-27 01:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeindex',
            name='about_bottom',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='about_bottom'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='about_middle',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='about_middle'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='about_top',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='about_top'),
        ),
    ]
