# Generated by Django 3.2.2 on 2021-06-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeportfolio',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
