# Generated by Django 3.2.2 on 2021-06-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePortfolio',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
            bases=('resume.resumepage',),
        ),
        migrations.CreateModel(
            name='ResumeService',
            fields=[
                ('resumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.resumepage')),
            ],
            options={
                'verbose_name': 'ResumeService',
                'verbose_name_plural': 'ResumeServices',
            },
            bases=('resume.resumepage',),
        ),
        migrations.CreateModel(
            name='ResumeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller', models.CharField(max_length=2000, verbose_name='teller')),
                ('teller_description', models.CharField(max_length=2000, verbose_name='teller_description')),
                ('title', models.CharField(max_length=2000, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=2000, null=True, verbose_name='متن')),
                ('footer', models.CharField(max_length=200, verbose_name='پانوشت')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('date_added', models.DateField(verbose_name='date_added')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='resume/img/Testimonial/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start_date'),
        ),
        migrations.CreateModel(
            name='ResumeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('typing_text', models.CharField(max_length=500, verbose_name='typing_text')),
                ('about_top', models.TextField(verbose_name='about_top')),
                ('job_title', models.CharField(max_length=300, verbose_name='job_title')),
                ('about_middle', models.TextField(verbose_name='about_middle')),
                ('birth_day', models.DateField(verbose_name='birth_day')),
                ('website', models.CharField(max_length=500, verbose_name='website')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('age', models.IntegerField(default=30, verbose_name='age')),
                ('degree', models.CharField(max_length=100, verbose_name='degree')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('freelance', models.CharField(max_length=100, verbose_name='freelance')),
                ('about_bottom', models.TextField(verbose_name='about_bottom')),
                ('resume_top', models.TextField(verbose_name='resume_top')),
                ('portfolio_top', models.TextField(verbose_name='portfolio_top')),
                ('services_top', models.TextField(verbose_name='services_top')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'ResumeIndex',
                'verbose_name_plural': 'ResumeIndexs',
            },
        ),
    ]
