# Generated by Django 3.2.2 on 2022-01-27 02:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20220127_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeindex',
            name='portfolio_top',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='portfolio_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='resume_top',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='resume_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='services_top',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='services_top'),
        ),
    ]
