# Generated by Django 3.2.2 on 2021-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumeskill_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeindex',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
    ]
