# Generated by Django 3.2.2 on 2021-06-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210627_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeindex',
            name='about_bottom',
            field=models.TextField(blank=True, null=True, verbose_name='about_bottom'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='about_middle',
            field=models.TextField(blank=True, null=True, verbose_name='about_middle'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='about_top',
            field=models.TextField(blank=True, null=True, verbose_name='about_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='age',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='birth_day'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='freelance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='freelance'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='job_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='job_title'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='portfolio_top',
            field=models.TextField(blank=True, null=True, verbose_name='portfolio_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='resume_top',
            field=models.TextField(blank=True, null=True, verbose_name='resume_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='services_top',
            field=models.TextField(blank=True, null=True, verbose_name='services_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='typing_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='typing_text'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='website'),
        ),
    ]
