# Generated by Django 3.2.2 on 2021-06-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumeportfolio_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeskill',
            old_name='persentage',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='resumefact',
            name='icon',
            field=models.CharField(choices=[('<i class="bi bi-emoji-smile"></i>', '<i class="bi bi-emoji-smile"></i>'), ('<i class="bi bi-journal-richtext"></i>', '<i class="bi bi-journal-richtext"></i>'), ('<i class="bi bi-headset"></i>', '<i class="bi bi-headset"></i>'), ('<i class="bi bi-award"></i>', '<i class="bi bi-award"></i>')], max_length=100, verbose_name='icon'),
        ),
    ]
