# Generated by Django 3.2.2 on 2021-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeindex',
            name='call',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='call'),
        ),
        migrations.AddField(
            model_name='resumeindex',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
    ]
