# Generated by Django 3.2.2 on 2021-07-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resumeindex_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeindex',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
    ]
