# Generated by Django 3.2.2 on 2021-06-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210627_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeindex',
            name='facts_top',
            field=models.TextField(blank=True, null=True, verbose_name='facts_top'),
        ),
        migrations.AddField(
            model_name='resumeindex',
            name='skills_top',
            field=models.TextField(blank=True, null=True, verbose_name='skills_top'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='typing_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='typing_text'),
        ),
    ]
