# Generated by Django 3.2.2 on 2021-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210627_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeindex',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='resume/img/Resume/Header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AddField(
            model_name='resumeindex',
            name='image_main_origin',
            field=models.ImageField(blank=True, null=True, upload_to='resume/img/Resume/Main/', verbose_name='تصویر اصلی'),
        ),
    ]
