# Generated by Django 3.2.2 on 2021-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resumeportfolio_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeportfolio',
            name='category',
            field=models.CharField(default='app', max_length=500, verbose_name='category'),
            preserve_default=False,
        ),
    ]
