# Generated by Django 3.2.2 on 2021-07-28 09:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
                ('class_name', models.CharField(max_length=50, verbose_name='class_name')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('year', models.IntegerField(verbose_name='سال ساخت')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/Property', verbose_name='image')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'FinancialAccount',
                'verbose_name_plural': 'FinancialAccounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_paid', models.DateTimeField(verbose_name='date_paid')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='ثبت کننده')),
                ('pay_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_from', to='accounting.financialaccount', verbose_name='pay_from')),
                ('pay_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_to', to='accounting.financialaccount', verbose_name='pay_to')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('bank', models.CharField(choices=[('بانک ملی', 'بانک ملی'), ('بانک ملت', 'بانک ملت'), ('بانک سپه', 'بانک سپه'), ('بانک رفاه', 'بانک رفاه'), ('بانک مسکن', 'بانک مسکن'), ('بانک توسعه تعاون', 'بانک توسعه تعاون')], max_length=50, verbose_name='bank')),
                ('branch', models.CharField(max_length=50, verbose_name='شعبه')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.financialaccount', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'BankAccount',
                'verbose_name_plural': 'BankAccounts',
            },
        ),
    ]
