# Generated by Django 3.2.2 on 2021-07-02 11:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_enabled'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('year_created', models.IntegerField(verbose_name='سال ساخت')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/Property', verbose_name='image')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='ثبت کننده'),
        ),
    ]
