# Generated by Django 3.2.2 on 2021-11-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='shaba_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا'),
        ),
    ]
