# Generated by Django 3.2.2 on 2021-10-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.transaction')),
            ],
            options={
                'verbose_name': 'MoneyTransaction',
                'verbose_name_plural': 'MoneyTransactions',
            },
            bases=('accounting.transaction',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_from_set', to='accounting.financialaccount', verbose_name='pay_from'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_to_set', to='accounting.financialaccount', verbose_name='pay_to'),
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.transaction')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.asset', verbose_name='asset')),
            ],
            options={
                'verbose_name': 'AssetTransaction',
                'verbose_name_plural': 'AssetTransactions',
            },
            bases=('accounting.transaction',),
        ),
    ]
