# Generated by Django 3.2.2 on 2021-07-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210702_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='year_created',
            new_name='year',
        ),
    ]
