# Generated by Django 3.2.2 on 2021-11-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20211102_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'دارایی ها'},
        ),
        migrations.AlterModelOptions(
            name='assettransaction',
            options={'verbose_name': 'AssetTransaction', 'verbose_name_plural': 'انتقال دارایی ها'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'BankAccount', 'verbose_name_plural': 'حساب های بانکی'},
        ),
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'verbose_name': 'FinancialAccount', 'verbose_name_plural': 'حساب های مالی'},
        ),
        migrations.AlterModelOptions(
            name='marketordertransaction',
            options={'verbose_name': 'MarketOrderTransaction', 'verbose_name_plural': 'تراکنش های صورت حساب فروش'},
        ),
        migrations.AlterModelOptions(
            name='moneytransaction',
            options={'verbose_name': 'MoneyTransaction', 'verbose_name_plural': 'تراکنش های پولی'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('بانک ملی', 'بانک ملی'), ('بانک ملت', 'بانک ملت'), ('بانک سپه', 'بانک سپه'), ('بانک رفاه', 'بانک رفاه'), ('بانک مسکن', 'بانک مسکن'), ('بانک توسعه تعاون', 'بانک توسعه تعاون')], max_length=50, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.financialaccount', verbose_name='صاحب حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
