# Generated by Django 3.2.2 on 2021-10-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20211030_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مالک'),
        ),
    ]
