# Generated by Django 3.2.2 on 2021-10-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20211030_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransaction',
            name='paymet_method',
            field=models.CharField(choices=[('وجه نقد', 'وجه نقد'), ('کارت به کارت', 'کارت به کارت'), ('واریزی بانک', 'واریزی بانک'), ('چک', 'چک')], default='کارت به کارت', max_length=50, verbose_name='paymet_method'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='class_name'),
        ),
    ]
