# Generated by Django 3.2.2 on 2021-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_year_created_asset_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='app_name',
            field=models.CharField(default='aaa', max_length=50, verbose_name='app_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='class_name',
            field=models.CharField(default='sdsd', max_length=50, verbose_name='class_name'),
            preserve_default=False,
        ),
    ]
