# Generated by Django 3.2.2 on 2021-10-30 21:09

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_link_new_tab'),
        ('market', '0002_auto_20211005_2349'),
        ('accounting', '0004_auto_20211030_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.Image', verbose_name='images'),
        ),
        migrations.CreateModel(
            name='MarketOrderTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.transaction')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'MarketOrderTransaction',
                'verbose_name_plural': 'MarketOrderTransactions',
            },
            bases=('accounting.transaction', accounting.models.TransactionMixin),
        ),
    ]
