# Generated by Django 3.2.2 on 2021-11-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_materialrequest_ware_house_sheets'),
        ('accounting', '0004_auto_20211120_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.transaction')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'ProjectTransaction',
                'verbose_name_plural': 'تراکنش های پروژه ها',
            },
            bases=('accounting.transaction',),
        ),
    ]
