# Generated by Django 3.2.2 on 2021-10-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20211030_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='description'),
        ),
    ]
