# Generated by Django 3.2.2 on 2022-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_projecttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('بانک ملی', 'بانک ملی'), ('بانک ملت', 'بانک ملت'), ('بانک سپه', 'بانک سپه'), ('بانک رفاه', 'بانک رفاه'), ('بانک صادرات', 'بانک صادرات'), ('بانک کشاورزی', 'بانک کشاورزی'), ('بانک مسکن', 'بانک مسکن'), ('بانک قرض الحسنه مهر ایران', 'بانک قرض الحسنه مهر ایران'), ('بانک توسعه تعاون', 'بانک توسعه تعاون')], max_length=50, verbose_name='بانک'),
        ),
    ]
