# Generated by Django 3.2.2 on 2021-11-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20211031_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='class_name'),
        ),
    ]
