# Generated by Django 3.2.2 on 2021-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_transaction_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytransaction',
            name='paymet_method',
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='payment_method',
            field=models.CharField(choices=[('وجه نقد', 'وجه نقد'), ('کارت به کارت', 'کارت به کارت'), ('واریزی بانک', 'واریزی بانک'), ('چک', 'چک')], default='کارت به کارت', max_length=50, verbose_name='payment_method'),
        ),
    ]
