# Generated by Django 3.2.2 on 2021-11-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_link_new_tab'),
        ('accounting', '0007_auto_20211101_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPage',
            fields=[
                ('basicpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicpage')),
            ],
            bases=('core.basicpage',),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='images',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='accountingpage_ptr',
            field=models.OneToOneField(auto_created=True, default=89, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingpage'),
            preserve_default=False,
        ),
    ]
